"""remove book specific fields

Revision ID: 2264cf922ab7
Revises: fea979322bbe
Create Date: 2025-12-18 14:03:18.705702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2264cf922ab7'
down_revision: Union[str, Sequence[str], None] = 'fea979322bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'isbn')
    op.drop_column('listings', 'course_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('course_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
