"""add_user_id_to_subscription

Revision ID: 8e0f7cf8f9a3
Revises: 9c5efffbc9f1
Create Date: 2025-12-18 12:35:44.815138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0f7cf8f9a3'
down_revision: Union[str, Sequence[str], None] = '9c5efffbc9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'user_id')
    # ### end Alembic commands ###
