"""add_user_id_to_subscription

Revision ID: bca3a2ff0304
Revises: 8e0f7cf8f9a3
Create Date: 2025-12-18 12:36:00.989550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca3a2ff0304'
down_revision: Union[str, Sequence[str], None] = '8e0f7cf8f9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
