"""add_location_to_listing

Revision ID: ddde4a629b5a
Revises: bca3a2ff0304
Create Date: 2025-12-18 12:40:07.451369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddde4a629b5a'
down_revision: Union[str, Sequence[str], None] = 'bca3a2ff0304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'location')
    # ### end Alembic commands ###
