"""add owner_id to listing

Revision ID: fea979322bbe
Revises: ddde4a629b5a
Create Date: 2025-12-18 13:58:14.855872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea979322bbe'
down_revision: Union[str, Sequence[str], None] = 'ddde4a629b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'listings', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'owner_id')
    # ### end Alembic commands ###
